[toolchain]
anchor_version = "0.29.0"
solana_version = "1.17.0"


[workspace]
members = ["programs/cp-swap"]

[features]
seeds = false
skip-lint = false

[programs.Localnet]
raydium_cp_swap = "8VFKZGTCxsGcCGpuGAAuKMW2qjhb4iGrHqEhwAqjBss5"
[programs.devnet]
raydium_cp_swap = "8VFKZGTCxsGcCGpuGAAuKMW2qjhb4iGrHqEhwAqjBss5"

[registry]
url = "https://github.com/raydium-io/raydium-cp-swap"

[provider]
# cluster = "https://solana-devnet.g.alchemy.com/v2/xWOhFt-Wncqb1FpIO1-4Tpu11R9anIHR"
# cluster  = "https://devnet.helius-rpc.com/?api-key=f1bdd519-fbd3-4a50-aeae-99f67bcc8bd3"
cluster = "Devnet"
# cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/mono.test.2.ts"
# test = "bun run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/mono.test.2.ts"

[test]
startup_wait = 10000

[test.validator]
# url = "https://api.mainnet-beta.solana.com"

# [[test.validator.clone]]
# address = "DNXgeM9EiiaAbaWvwjHj9fQQLAX5ZsfHyvmYUNRAdNC8"

# [[test.validator.clone]]
# address = "D4FPEruKEHrG5TenZ2mpDGEfu1iUvTiqBxvpU8HLBvC2"
